version: "3.8"

services:
  app:
    build:
      context: ./app
    container_name: app
    ports:
      - "5000:5000"
    environment:
      DB_URI: "mysql+mysqlconnector://flask_user:password@mysql/flask_app_db"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  prometheus:
    build:
      context: ./prometheus
      platforms:
        - linux/arm64
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "9090:9090"

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  volumes:
    - grafana-storage:/var/lib/grafana
    - ./grafana/config.ini:/etc/grafana/grafana.ini
    - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
    - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    - ./grafana/dashboards:/var/lib/grafana/dashboards
  depends_on:
    - prometheus

volumes:
  mysql_data:
  grafana-storage:
