version: "3.8"

services:
  app:
    build:
      context: ./app
      platforms:
        - linux/amd64
    container_name: app
    ports:
      - "5000:5000"
    environment:
      DB_URI: "mysql+mysqlconnector://flask_user:password@mysql/flask_app_db"
    depends_on:
      - mysql
    platform: linux/amd64

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    platform: linux/amd64

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    platform: linux/amd64

  prometheus:
    build:
      context: ./prometheus
      platforms:
        - linux/amd64
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "9090:9090"
    depends_on:
      - app
    platform: linux/amd64

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    platform: linux/amd64

volumes:
  mysql_data:
  grafana-storage:
