{
 "title": "Example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Total Apps flask", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AVG Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{job=\"flask_apps\"})\r\n",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "AVG CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"flask_apps\"}[$__rate_interval]))\r\n",
     "legendFormat": "cpu"
    }
   ]
  },
  { "title": "Apps Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Requests per minute",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[5m])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"500\"}[30s]) )",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job='flask_apps'}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Duration Request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{job=\"flask_apps\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\"}[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job='flask_apps'}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{job=\"flask_apps\", method=\"GET\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency apps",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flask_request_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}